package com.group91.tars.i18n;

import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.MissingResourceException;
import java.util.PropertyResourceBundle;
import java.util.ResourceBundle;

/**
 * Internationalisation utility providing locale-aware message translation.
 * Loads messages from UTF-8 encoded {@code .properties} files and supports
 * positional parameter substitution via {@link MessageFormat}.
 */
public class I18n {
    private static final String BASE_NAME = "i18n.messages";

    /** Custom ResourceBundle.Control that reads properties files as UTF-8. */
    private static final ResourceBundle.Control UTF8_CONTROL = new ResourceBundle.Control() {
        @Override
        public ResourceBundle newBundle(String baseName, Locale locale, String format,
                                         ClassLoader loader, boolean reload)
                throws IllegalAccessException, InstantiationException, IOException {
            if ("java.properties".equals(format)) {
                String resourceName = toResourceName(toBundleName(baseName, locale), "properties");
                InputStream stream = loader.getResourceAsStream(resourceName);
                if (stream != null) {
                    try (Reader reader = new InputStreamReader(stream, "UTF-8")) {
                        return new PropertyResourceBundle(reader);
                    }
                }
            }
            return super.newBundle(baseName, locale, format, loader, reload);
        }
    };

    private final ResourceBundle bundle;
    private final Locale locale;

    /**
     * Constructs an I18n instance for the given locale.
     *
     * @param locale the target locale for message translation
     */
    public I18n(Locale locale) {
        this.locale = locale;
        ResourceBundle.clearCache(Thread.currentThread().getContextClassLoader());
        this.bundle = ResourceBundle.getBundle(BASE_NAME, locale, UTF8_CONTROL);
    }

    /**
     * Retrieves the I18n instance stored as a request attribute by BasePageServlet.
     *
     * @param request the HTTP request containing the "i18n" attribute
     * @return the I18n instance
     */
    public static I18n fromRequest(HttpServletRequest request) {
        return (I18n) request.getAttribute("i18n");
    }

    /**
     * Translates a message key to the current locale's text.
     * Returns {@code "!KEY!"} as a visible fallback when the key is not found.
     *
     * @param key the i18n property key
     * @return the translated string, or "!key!" if not found
     */
    public String t(String key) {
        try {
            return bundle.getString(key);
        } catch (MissingResourceException e) {
            return "!" + key + "!";
        }
    }

    /**
     * Translates a message key with positional parameters using {@link MessageFormat}.
     *
     * @param key  the i18n property key
     * @param args positional arguments to substitute into the pattern
     * @return the formatted translated string
     */
    public String t(String key, Object... args) {
        String pattern = t(key);
        return MessageFormat.format(pattern, args);
    }

    /**
     * Translates seeded/demo data values only for the Chinese UI.
     * English keeps the original JSON text so the English version is not affected.
     *
     * @param value data text loaded from JSON or generated by the service layer
     * @return translated text for Chinese locale, otherwise the original value
     */
    public String td(String value) {
        if (value == null) {
            return "";
        }
        if (!"zh".equals(locale.getLanguage())) {
            return value;
        }

        String trimmed = value.trim();
        if (trimmed.startsWith("The PDF CV/profile evidence mentions: ") && trimmed.endsWith(".")) {
            String evidence = trimmed.substring("The PDF CV/profile evidence mentions: ".length(), trimmed.length() - 1);
            return t("data.cv-evidence-mentions", evidence);
        }
        if (trimmed.startsWith("The TA should address these gaps before applying or explain related experience: ")
            && trimmed.endsWith(".")) {
            String gaps = trimmed.substring(
                "The TA should address these gaps before applying or explain related experience: ".length(),
                trimmed.length() - 1
            );
            return t("data.ta-should-address-gaps", gaps);
        }
        if (trimmed.matches("At the workload cap \\(\\d+/\\d+\\)\\. Avoid assigning more accepted jobs\\.")) {
            String count = trimmed.substring(trimmed.indexOf('(') + 1, trimmed.indexOf(')'));
            return t("data.at-workload-cap", count);
        }
        if (trimmed.matches("Near the workload cap \\(\\d+/\\d+\\)\\. Use caution before accepting another application\\.")) {
            String count = trimmed.substring(trimmed.indexOf('(') + 1, trimmed.indexOf(')'));
            return t("data.near-workload-cap", count);
        }
        if (trimmed.matches("Normal workload \\(\\d+/\\d+\\)\\. Capacity is available\\.")) {
            String count = trimmed.substring(trimmed.indexOf('(') + 1, trimmed.indexOf(')'));
            return t("data.normal-workload", count);
        }
        if (trimmed.matches(".+ status is .+\\.")) {
            int statusIndex = trimmed.lastIndexOf(" status is ");
            String title = trimmed.substring(0, statusIndex);
            String status = trimmed.substring(statusIndex + " status is ".length(), trimmed.length() - 1);
            return t("data.application-status-is", title, statusLabel(status));
        }
        if (trimmed.matches("You can still apply for \\d+ more job\\(s\\)\\.")) {
            String count = trimmed.replaceAll("\\D+", "");
            return t("data.remaining-applications", count);
        }

        String key = "data." + value.trim()
            .toLowerCase(Locale.ENGLISH)
            .replaceAll("[^a-z0-9]+", "-")
            .replaceAll("^-+|-+$", "");
        try {
            return bundle.getString(key);
        } catch (MissingResourceException e) {
            if (trimmed.contains(",")) {
                String[] parts = trimmed.split("\\s*,\\s*");
                StringBuilder translated = new StringBuilder();
                for (int index = 0; index < parts.length; index++) {
                    if (index > 0) {
                        translated.append("、");
                    }
                    translated.append(td(parts[index]));
                }
                return translated.toString();
            }
            return value;
        }
    }

    private String statusLabel(String status) {
        String key = "status." + status.toLowerCase(Locale.ENGLISH).replace(" ", "-");
        String translated = t(key);
        return translated.startsWith("!status.") ? status : translated;
    }

    /**
     * Returns the two-letter language code of the current locale.
     *
     * @return language code (e.g. "en", "zh")
     */
    public String getLanguage() {
        return locale.getLanguage();
    }
}
